CommandFailed=cd命令执行失败
TFTPFileFailed=tftp获取文件失败
UnpackFailure=解压缩失败
FileDeletionFailed=文件删除失败
PleaseLoginMachine=请先telnet登录设备
OperationFailed=操作失败,请确认升级文件格式是否正确!
SelectUpgradeFile=请先选择升级文件!
SelectUpgradeOptions=请先选择升级选项!
MustUpgraded=文件夹中无升级文件
LicenseUpFailed=许可文件升级失败
LicenseUpIng=许可文件升级
LicenseObtainSuccess=许可文件获取成功
LicenseObtainfailed=许可文件获取失败
LicenseLogSuccess=许可日志获取成功
LicenseLogFailed=许可日志获取失败
LicensePath=打开许可存放目录
NotDeviceLicenseDerict=无此机器的许可升级文件夹
DeviceNoFialed=机器序列号读取失败
LanguageUpFailed=语言文件升级失败
LanguageUpIng=语言文件升级
FPLicenseUpFailde=指纹许可升级失败
FPLicenseUpIng=指纹许可升级
UDiskKernalBoardWait=等待设备启动
DeviceRestart=设备重启成功
DeviceConFailed=设备连接失败,请检查设备固件是否已经正常启动!
DeviceConFailedReCon=设备连接失败,请连接设备!
DeviceConFailedPWD=考勤固件连接密码错误!
TFTPUpload=tftp传送
FileFailed=文件失败
Success=成功
Failed=失败
Upgrade=升级
FirmUp=固件升级firmware update
RestoreDataCompleteRebootAttention=操作成功,重新启动设备后数据生效，是否重新启动设备!
RestoreDataAttention=此操作会覆盖设备原有相关数据，确认还原相关数据吗？

UpgradeFileAlreadyExists=文件已经存在，是否覆盖原有文件!
FileMakeFailed=文件制作失败
UpFileFormatFailed=升级文件格式不正确!

IPAddr=设备IP地址
UserName=系统登录用户名
PWD=系统登录密码
SDKConnect=设备固件连接
ConPWD=设备固件连接密码
StateNoLogin=未登录设备
StateNoCon=未连接设备
StateYesLogin=已登录设备
StateYesCon=已连接设备
Login=系统登录
Con=固件连接
ConRefresh=重新登录连接
ConIpError=PC机与考勤设备网络地址需在同一网段,请设置PC机tftp服务IP或考勤设备IP地址!
ConInitDev=正在初始化数据
ConFailed=连接失败，请检查线路连接是否正常!
LoginConSeccese=设备登录连接成功!
UserOrPWDFailed=设备系统登录用户名或密码错误!
TelnetLoginFailed=设备系统登录失败!
DevFirmConFailed=设备固件连接失败!

IllegalIPAddr=非法IP地址
IPAddrNotNull=IP地址不能为空
IllegalPassword=密码中含有非法字符，设备固件连接密码由数字（0~9）组成!
ParamNotNull=参数名或参数不能为空
ParamValueFailed=参数默认值错误
IllegalSymbol=输入有非法符号，请检查输入的字符串!

DevNoConnect=设备未连接
DevFirmNoConnect=设备固件未连接
DevNoThisFile=考勤设备无此文件

FileUpload=文件正在传送
FIleReceive=文件正在接收
DataProcessing=数据处理
DataLoading=数据加载
GetLicenseFile=正在获取许可文件
GetLicenseLog=正在获取许可日志
Attention=注意
FilePath=文件路径


FirmDirectoryPath=选择的文件夹不正确，请重新选择.
FirmDirPathAttention=请先选择本地文件路径

CompressedPackageError=压缩包格式不正确

AdministratorAttention=软件未获取管理员权限不能正常工作，请设置程序拥有管理员权限!
ProgramRunAttention=本程序一次只能运行一个实例!



UpdataIng=正在升级
LicenseUp=许可操作


ObtainLicense=获取
ObtainLicenseEx=获取许可文件或日志
LicenseLog=获取许可日志


UpSuccesse=升级成功
GetDevPlantAttention=设备平台信息获取失败
UpPackageHeadError=升级包头格式错误
UpPackageTextError=升级包不包含此机器序列号
UpPackagePlantError=升级失败，请使用正确的固件平台升级包
UpPackageDevError=设备固件不支持此功能

ParamSet=参数设置


SelectedFileNotConformityEX=文件要求{0}格式,请重新选择!
SelectedFileNotConformity=文件格式错误,请重新选择!

ParamSetSuccess=重启后设备正常工作！
